### ISSUE TITLE
Optimize load time

### ISSUE THREAD

**Issue by niutech** [niutech/typescript-compile#1]
Since version 0.2, TypeScript Compile includes a huge definition file _lib.d.ts_, which is compressed by packer, but still weights >100KB and must be compiled on the fly, before user scripts.

I can get rid of it, but then the compiler will throw many errors, e.g. _"The name 'IArguments' does not exist in the current scope"_, although the script will compile and run.

What to do you think about it? Should I remove _lib.d.ts_?

**Comment by pstjvn** [comment]
Removing the definition types will not benefit your project, who would want to compile code that is not browser related in the browser? 
If that is your aim however, you can always strip all host related stuff and make your own definition file with just the javascript definitions, like Function etc. It will be much smaller and completely useless.

**Comment by jbaron** [comment]
What about making it optional. So you would have a "checked version" that does all the type checking of types and generate warnings (great for development). 

And an "unchecked version" that omits the lib.d.ts file and the compiler can even skip any type-checks and only generates the required javascript (great for production mode). This would also compile much faster.

**Comment by pstjvn** [comment]
Consider this: it will never work as fast as javascript because:
1) the source is often larger than the compiled JS (interfaces for example are completely stripped, as well as type information, the word 'prototype' is instead presented, but the source being gzipped by the server negates this
2) JS can be minified effectively, I am not sure about TS, but probably not yet.
3) The compiler must run, create AST, spill out JS and then the JS can be evaluated, this seems like much more work than just parsing pure JS.

This said I think you should omit support for production at this stage, I honestly believe no one will put this on production until at least it hits 1.0.

**Comment by niutech** [comment]
Thank you for your opinions. I agree that TypeScript Compile will not be as fast as pure JavaScript, but the most important part is the simplicity of embeding TypeScript code directly into a web browser. And now it's performing almost as fast as JS.

In version 0.3, I have split TypeScript Compile into two versions: _dev.js_ and _min.js_, the latter without the _lib.d.ts_ definition file, what makes compilation really fast. To optimize it even more, I have added a simple cache of compiled JS code in _sessionStorage_ to both files, so the code gets compiled only once a session.

Please give it a try and tell me what you think of it. Greetings!

**Comment by pstjvn** [comment]
The example is not working, I don't have time to debug, but the problem is the extending classes are not actually extended in the resulting code:

I downloaded the source from github cloning, fired a simple web server and loaded demo.html. It says:
Uncaught ReferenceError: _super is not defined : demo.html : 36

In the generated source code
__extend is never defined not attempted use is seen, except in methods looking for _super. 

If I compile it in the console with 'tsc demo.ts' extending is working as expected -> the compilation in the browser is broken. Sorry

Goog luck

**Comment by jbaron** [comment]
FYI 

I get the same error (Chrome on Linux), The following is the generated JS and it indeed is missing the __extend function. If you use extend, the compiler automatically should define this method at the top of the file and of course use it in the different code sections. This is the only runtime component that I'm aware of that typescript generates (and a very small one).  

//Compiled TypeScript

var Sayings;
(function (Sayings) {
    var Greeter = (function () {
        function Greeter(message) {
            this.greeting = message;
        }
        Greeter.prototype.greet = function () {
            return "Hello, " + this.greeting;
        };
        return Greeter;
    })();
    Sayings.Greeter = Greeter;  
})(Sayings || (Sayings = {}));

var greeter = new Sayings.Greeter('world');
var button = document.createElement('button');
button.innerHTML = "Say Hello";
button.onclick = function () {
    alert(greeter.greet());
};
document.body.appendChild(button);
var Animal = (function () {
    function Animal(name) {
        this.name = name;
    }
    Animal.prototype.move = function (meters) {
        alert(this.name + " moved " + meters + "m.");
    };
    return Animal;
})();
var Snake = (function () {
    function Snake() { }
    Snake.prototype.move = function () {
        alert("Slithering...");
        _super.prototype.move.call(this, 5);
Uncaught ReferenceError: _super is not defined (repeated 2 times)
Uncaught ReferenceError: _super is not defined
    };
    return Snake;
})();
var Horse = (function () {
    function Horse() { }
    Horse.prototype.move = function () {
        alert("Galloping...");
        _super.prototype.move.call(this, 45);
    };
    return Horse;
})();
var sam = new Snake("Sammy the Python");
var tom = new Horse("Tommy the Palomino");
var but = document.createElement('button');
but.innerHTML = "Animal run";
but.onclick = function () {
    sam.move();
    tom.move(34);
};
document.body.appendChild(but);

**Comment by niutech** [comment]
You're right, there was a bug when ommiting the definition file and I missed that, but I have just fixed this bug by adding a minimal _lib.d.ts_ file with only the most important interfaces, like IArguments, Object, String, Date, Function, Window, Document, etc. It seems to work fine now, there are no compilation errors and the script size is decent.

**Comment by niutech** [comment]
Closing as the code is pretty optimized and it seems to be working nice.
